---
controller_schedules:
  - name: Delete Daily Demo Network
    description: Schedule to run the demo playbook once a day at 6:00 pm
    rrule: DTSTART;TZID={{ timezone_id }}:20230101T180000 RRULE:FREQ=DAILY;INTERVAL=1
    unified_job_template: "Daily Demo Network Create/Remove"
    state: present
    job_tags: remove
