---
controller_credentials:
- name: AWS ubuntu machine credential
  description: ssh key based authentication
  organization: "{{ my_organization }}"
  credential_type: Machine
  inputs:
    username: ubuntu
    ssh_key_data: "{{ ssh_priv_key }}"
    become_method: sudo
